# Generated by Django 3.1.6 on 2021-03-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture4',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture5',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture6',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
